swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Auth Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - Auth Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{AccountId}/AllTransaction:
    get:
      security:
        - Bearer: []
      tags:
        - transaction Module
      summary: View User Transactions
      description: API for viewing user transactions by account
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: AccountId
          type: integer
          description: (Optional) Account ID for which transactions are to be fetched
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{AccountId}/transaction/{Id}:
    get:
      security:
        - Bearer: []
      tags:
        - transaction Module
      summary: View a Single Transaction
      description: API for viewing a single transaction by its transaction ID
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: AccountId
          required: true
        - in: path
          type: string
          name: Id
          description: Transaction ID for the transaction to be fetched
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/{AccountId}/transactionmonth/{MM-YY}:
    get:
      security:
        - Bearer: []
      tags:
        - transaction Module
      summary: View a Single Transaction
      description: API for viewing a single transaction by its transaction ID
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: AccountId
          required: true
        - in: path
          type: string
          name: MM-YY
          description: Transaction by month i.e:MM-YY
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/{AccountId}/Transaction/{transactionId}/note:
    patch:
      summary: Update information of a transaction note
      security:
        - Bearer: []
      tags:
        - transaction Module
      parameters:
        - name: AccountId
          in: path
          description: ID of the AccountId
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - name: Note
          in: body
          description: Object representing the new transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdateNote"
      responses:
        200:
          description: Success - Transaction successfully updated
        400:
          description: Bad Request - Data validation error
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbiden
        404:
          description: Transaction not found - Invalid transaction ID
        500:
          description: Internal Server Error
  /user/{AccountId}/Transaction/{transactionId}/Category:
    patch:
      summary: Update information of a transaction Category
      security:
        - Bearer: []
      tags:
        - transaction Module
      parameters:
        - name: AccountId
          in: path
          description: ID of the AccountId
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - name: Category
          in: body
          description: Object representing the category transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdateCategory"
      responses:
        200:
          description: Success - Transaction successfully updated
        400:
          description: Bad Request - Data validation error
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbiden
        404:
          description: Transaction not found - Invalid transaction ID
        500:
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionUpdateNote:
    type: object
    properties:
      note:
        type: string
        description: Additional note for the transaction
  TransactionUpdateCategory:
    type: object
    properties:
      category:
        type: string
        description: update Category of the transaction
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: ID of the transaction to be updated
      date:
        type: string
        description: Transaction date
      type:
        type: string
        description: Transaction type
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Balance of the account at the time of the transaction
      category:
        type: string
        description: Transaction category
        enum:
        - Food
        - Transportation
        - Shopping
        - Entertainement
        - Other
      note:
        type: string
        description: Additional notes for the transaction